### PR TITLE
add command options for help and version

### LINKED ISSUE #36: Add command options for help and version.
Add -h and -V options

Basic `getopts` version:

```bash
  #-----------------------------------------------------------------------
  #  Handle command line arguments
  #-----------------------------------------------------------------------
  while getopts ":hV" opt
  do
    # shellcheck disable=SC2214
    case "${opt}" in

      h|help      ) _usage;    exit 0 ;;
      V|version   ) _version;  exit 0 ;;

      \?  ) printf '\nInvalid option: %s\n\n' "${OPTARG}"
            _usage;    exit 2 ;;

    esac    # --- end of case ---
  done
  shift $(( OPTIND-1 ))
```

### PR DESCRIPTION
**Pull request by ptt-homme**
Fix #36 

Hope this helps.

### CODE REVIEW

**Comment by kdabir** [comment]
Could you please make sure the tests pass with the commit? Happy to merge this once tests are updated.

**Comment by ptt-homme** [comment]
Sure, I will!

Was my plan anyway to fix the CI :)

**Comment by ptt-homme** [comment]
@kdabir 

Tests are fixed now.
I added a new test to check if the usage message is printed when the flag `-q` is present and there is no `.hasrc` file or commands given.

I was wondering, would you let me rewrite the tests using [bats-assert](https://github.com/ztombol/bats-assert) and [bats-support](https://github.com/ztombol/bats-support)? This will make writing tests less tedious (Ex. when comparing output).

**Comment by kdabir** [comment]
Sure, if makes the life easier for everyone, why not.

**Comment by ptt-homme** [comment]
Great! I'll open a new PR with it.

This one can be merged :) 

What are the rules to bump the version number ?

**Comment by ptt-homme** [comment]
@kdabir Any news about the project, is it still under development?

**Comment by kdabir** [comment]
Hey sorry for the silence on this PR since CI was failing I thought this is still work in progress.

**Pull request merged**
